YotubeアプリでAPI通信
onishitaisei/flutter-training pull request #10
Opened 2022-01-17 07:13 UTC by onishitaisei

2022-01-17 07:40 UTC, onishitaisei commented on lib/youtube/youtube_screen.dart
> -                            width: 180,
右側に`overflow`のエラーが発生していたので、サイズを調整。

2022-01-17 07:40 UTC, onishitaisei commented on lib/mvvm/model/qiita_item.freezed.dart
>  /// @nodoc
今回のタスクとは関係ないファイル、また、再生成可能なファイルのため、一旦削除。

2022-01-17 09:18 UTC, gitknkn commented on lib/mvvm/youtube_client_state_notifier.dart
> +      );
if (youtubeInformations.isNotEmpty) {,,,} else {,,,}
`youtubeInformations`配列の要素に応じて、条件分岐を作成されていますが、
配列の要素がない場合（今回だと、else側）、`youtubeInformation: [],`みたいな感じで明示的に空配列を指定した方がわかりやいかもと思いました！
動作的にはかわらないと思うので、参考程度で大丈夫です！

2022-01-18 00:39 UTC, t-nakata requested changes

2022-01-18 00:39 UTC, t-nakata commented on .gitignore
> +youtube_client_state.freezed.dart
自動生成ファイル一つ一つに対して列挙していくのは効率が悪いのでワイルドカードを使ってください。

2022-01-18 00:39 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +      ],
![badge](https://img.shields.io/badge/review-must-red.svg)
スクロール領域が動画Listだけになっているのが気になりました。
カテゴリメニューと動画Listがスクロール対象となるように修正してください。

2022-01-18 03:01 UTC, onishitaisei commented on lib/mvvm/youtube_client_state_notifier.dart
> +      );
@gitknkn 
ありがとうございます！
こちら他の修正と合わせて修正いたしました...!

2022-01-18 03:02 UTC, gitknkn approved these changes

2022-01-18 04:04 UTC, onishitaisei commented on .gitignore
> +youtube_client_state.freezed.dart
@t-nakata 
ワイルドカードを使用して、`freezed.dart`と`g.dart`ファイルをgit管理対象外に指定しました。

2022-01-18 04:05 UTC, onishitaisei commented on lib/youtube/youtube_screen.dart
> +      ],
@t-nakata 
こちら`ListView`内に`GridMenus`を指定して、`index`が0の場合のみ`GridMenus`を表示させる（メイン画面の上部のみ）ように修正いたしました！

2022-01-18 04:14 UTC, t-nakata approved these changes
Approveしますが、1件質問追加しました。
確認お願いします。

2022-01-18 04:14 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +                      youtubeInformation[index].imagePath.toString(),
`.toString()`を追加しているのはLint対応でしょうか？

おそらくですが `imagPath`がNullableなのでunwrapする必要があるのではないかと思いました。
そもそも、モデル側でNullableにしておく必要はありますか？

2022-01-18 04:35 UTC, onishitaisei commented on lib/youtube/youtube_screen.dart
> +                      youtubeInformation[index].imagePath.toString(),
@t-nakata 
`.toString`につきましては、Lintでの対応ではなく、おっしゃるNullableしていたための対応でございます。Nullableについては前回のQiitaアプリの惰性でつけてしまったものなので、非null許容型に修正いたしました..！次回以降気をつけます。approveを頂いているので、マージいたします。

2022-01-18 04:35 UTC, merged

2022-01-18 04:47 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +                      youtubeInformation[index].imagePath.toString(),
@onishitaisei 
`toString()`にunwrapの効果はなかったはずなので、こういった場合は`toString()`するのではなく
`imagePath?.toString() ??  ''`かな？ 意味合い的には、 `imagPath?.toString()`で `imagePath`がnullでなければ`toString()`した値を返す。 `imagePath`がnullであれば ''を返す。

2022-01-18 05:04 UTC, onishitaisei commented on lib/youtube/youtube_screen.dart
> +                      youtubeInformation[index].imagePath.toString(),
@t-nakata 
ありがとうございます！参考にさせていただきます！