Youtube画面の模写
onishitaisei/flutter-training pull request #2
Opened 2022-01-05 09:54 UTC by onishitaisei

### 概要
Flutter社内研修Tutorial2.1のYoutube画面の模写を行いました。

レイアウトは
○ヘッダー
○グリッドメニュー
○急上昇動画
○ボトムナビゲーション
で分割を行い、各項目ごとにWidgetの切り出し、コミットを行いました。

## 動作確認
急上昇動画部分はListViewで表示し、正しく動作することを確認しました。

## その他
模写した画面のスクリーンショットを添付いたします。

<img width="397" alt="youtube_screen" src="https://user-images.githubusercontent.com/97043781/148196967-b5a3c14b-fce6-4379-b7f7-9844d5cb2c8d.png">

2022-01-05 10:09 UTC, t-nakata requested changes

2022-01-05 10:09 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  List<Color> gridColor = [
外から参照する必要にない変数・関数はprivateで宣言してください

2022-01-05 10:09 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  List<String> movieText = [
外から参照する必要にない変数・関数はprivateで宣言してください

2022-01-05 10:09 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  List<String> movieImg = [
外から参照する必要にない変数・関数はprivateで宣言してください

2022-01-05 10:09 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  List<String> channelName = [
外から参照する必要にない変数・関数はprivateで宣言してください

2022-01-05 10:09 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  List<int> views = [127, 127];
外から参照する必要にない変数・関数はprivateで宣言してください

2022-01-05 10:09 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  List<int> dayPrevious = [1, 1];
外から参照する必要にない変数・関数はprivateで宣言してください

2022-01-05 10:09 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  Widget header() {
外から参照する必要にない変数・関数はprivateで宣言してください

あとメソッド名は基本的には 動詞  + 名詞 になります。
この場合は buildHeader や createHeaderという命名が一般的になります。

2022-01-05 10:09 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  Widget youtubeIcon() {
外から参照する必要にない変数・関数はprivateで宣言してください

こちらも同上 buildYoutubeIcon等

2022-01-05 10:09 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  Widget headerIcons() {
外から参照する必要にない変数・関数はprivateで宣言してください

こちらも同上

2022-01-05 10:09 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  Widget gridMenus() {
外から参照する必要にない変数・関数はprivateで宣言してください

2022-01-05 10:09 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  Widget gridMenus() {
命名も buildGridMenus等

2022-01-05 10:09 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  Widget gridMenu(int index) {
外から参照する必要にない変数・関数はprivateで宣言してください
同上

2022-01-05 10:09 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  Widget mainScreen() {
外から参照する必要にない変数・関数はprivateで宣言してください

2022-01-05 10:09 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  Widget mainMovies() {
外から参照する必要にない変数・関数はprivateで宣言してください
同上

2022-01-05 10:11 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  List<int> views = [127, 127];
変数名も意味の通る命名に修正してください。

Viewsだと Viewが複数あると考えるのに中身がIntでは意味が通らなくなります

2022-01-05 10:11 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  Widget mainScreen() {
これも命名

2022-01-05 13:09 UTC, Ryota-Nakamura-317 reviewed
少しだけコメントしています！

2022-01-05 13:09 UTC, Ryota-Nakamura-317 commented on lib/flutter_tutorial_screen.dart
>        padding: const EdgeInsets.all(32),
Containerに対してpaddingしかパラメータ設定してないのであれば、PaddingWidgetを使用するのが良いと思います。

2022-01-05 13:09 UTC, Ryota-Nakamura-317 commented on lib/youtube/youtube_screen.dart
> +          ],
YouTubeロゴとかの部分をheader()としていると思うのですが、appBarで実装してみるとより勉強になるのではと思いました！

2022-01-05 13:09 UTC, Ryota-Nakamura-317 commented on lib/youtube/youtube_screen.dart
> +                ]),
細かいですが、Stackのchildrenの最後にカンマほしいです！そちらのほうが見やすいかと思います！

2022-01-05 13:10 UTC, gitknkn commented on lib/youtube/youtube_screen.dart
> +                ]),
`]),` → `],),` 
このように ,(カンマ)を打った方がコード見やすくなるかと思います。

2022-01-06 00:18 UTC, gitknkn commented on lib/youtube/youtube_screen.dart
> +                                      color: movieTextColor, fontSize: 13),
`fontSize: 13`の後ろにカンマをつけた方が、コードが見やすくなるかなと思いました。

2022-01-06 00:18 UTC, gitknkn commented on lib/youtube/youtube_screen.dart
> +                                      color: movieTextColor, fontSize: 13),
こちらも同じくカンマがほしいです。

2022-01-06 00:18 UTC, gitknkn commented on lib/youtube/youtube_screen.dart
> +                                      color: movieTextColor, fontSize: 13),
こちらも同じくカンマがほしいです。

2022-01-06 01:48 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +                                      color: movieTextColor, fontSize: 13),
```
style: TextStyle(
    color: movieTextColor, 
    fontSize: 13,
),
```

2022-01-06 04:23 UTC, onishitaisei commented on lib/youtube/youtube_screen.dart
> +  Widget mainMovies() {
@t-nakata 
お疲れ様です！レビューいただきありがとうございました。
レビューで指摘していただきました部分を修正しましたので、ご確認お願いいたします。

2022-01-06 04:24 UTC, onishitaisei commented on lib/youtube/youtube_screen.dart
> +          ],
お疲れ様です！レビューいただきありがとうございました。
レビューで指摘していただきました部分の修正とappbarを使用したヘッダーを作成致しましたので、ご確認お願いいたします。

2022-01-06 04:25 UTC, onishitaisei commented on lib/youtube/youtube_screen.dart
> +                                      color: movieTextColor, fontSize: 13),
お疲れ様です！レビューいただきありがとうございました。
レビューで指摘していただきましたカンマの追加を行いましたので、ご確認お願い足します。

2022-01-06 04:27 UTC, onishitaisei commented on lib/youtube/youtube_screen.dart
> +          ],
上記の変更により、ヘッダーのレイアウトが少し変わりましたのでスクリーンショットを添付いたします。
<img width="402" alt="スクリーンショット 2022-01-06 13 20 26" src="https://user-images.githubusercontent.com/97043781/148328046-3015235c-1b12-4dbe-b97e-3acf5e59be71.png">

2022-01-06 04:34 UTC, Ryota-Nakamura-317 approved these changes

2022-01-06 04:41 UTC, gitknkn commented on lib/youtube/youtube_screen.dart
> +        // タイトルテキスト
`// タイトルテキスト`
このコメントは、何に対してのコメントでしょうか？

2022-01-06 04:44 UTC, t-nakata approved these changes
コメントしました、修正はしてほしいですが、再レビューは不要です。

2022-01-06 04:44 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +class YoutubeScreenPage extends StatelessWidget {
見逃してた、dartのファイル名とクラス名は基本合わせるようにしてください。
今回の場合は `YoutubeScreen`クラスと修正してください

2022-01-06 04:47 UTC, onishitaisei commented on lib/youtube/youtube_screen.dart
> +        // タイトルテキスト
見落としてました..
こちらmain.dartからappbarをコピペしたときについたコメントかと思います。
不要なコメントですので、youtube_screen.dartファイルと併せてmain.dartファイルのコメントも削除いたします。

2022-01-06 04:50 UTC, onishitaisei commented on lib/youtube/youtube_screen.dart
> +class YoutubeScreenPage extends StatelessWidget {
クラス名の修正の件、承知いたしました！
修正致します。

2022-01-06 04:54 UTC, onishitaisei commented on lib/youtube/youtube_screen.dart
> +        // タイトルテキスト
不要なコメントを削除いたしましたので、ご確認お願いいたします。

2022-01-06 04:56 UTC, gitknkn approved these changes

2022-01-06 04:58 UTC, merged