Tutorial5 - MVVMを学ぶについて
onishitaisei/flutter-training pull request #9
Opened 2022-01-13 11:43 UTC by onishitaisei

### 概要
Flutter社内研修Tutorial5「MMVMについて学ぶ」

理解できているか不安なので、こちらに情報を整理します。
認識に誤りがありましたら、ご指摘いただけますと幸いです...

- 実装方法

①Modelを作成
役割：APIで取得した値を持たせる
・APIでJSON型のデータが返ってくるため、`json_serializable` を使用してJSON⇄オブジェクトを変換(パースする？)
・`@JsonKey` を使用することで定数名を指定することができる
・freezed パッケージを使用することでimmutableなクラスの実装が楽になる（理解度は低いです..）
・`build_runner`を実行することにより、 `part ~`で指定したファイルが作成される。

②Repositoryを作成
役割：DBとのやりとりやAPI通信を行うメソッドを実行
・グローバル変数として指定することにより、`StateNotifier` 側で`Repository`で作成したメソッドを実行することができる
・`return _api.fetchQiitaItems(tag);`でAPI通信を実行。結果を`StateNotifier` に返却。

③API通信周りの実装
役割：実際にAPI通信を行い、取得した値をモデルに格納。
・API通信を行う。
・`Dio()`は取得したJSONの中身を見たい時に使用。
・やりとりはRepositoryのみ

④変更を検知するため、変更を監視したい部分を作成
役割：モデルに格納されたデータとそのほか監視したい状態を格納
・実際に表示させるデータやロード状態などを格納しておく

⑤ViewModel（StateNotifier）を作成
役割：ViewとModelの仲介役
・`QiitaClientState` を継承することによって、親クラスである`QiitaClientState` のプロパティを参照することができる。
・参照したプロパティをこのクラスで変更
・API通信の結果によって条件分岐。`fetchQiitaItems`メソッドが実行された瞬間に新たにfreezedによって生成された`QiitaClientState`の `isLoading`を `true`に。ロード画面が表示される

⑥Viewを作成
役割：実際に画面を表示させる
・freezedによってコピーされた`QiitaClientState`の状態によって画面の表示を変更。

### その他

実際に動作している動画を添付いたします。

https://user-images.githubusercontent.com/97043781/149323912-af7af045-22d4-4571-ab54-e6b772cdafde.mov

### 参考
○[【Flutter】Retrofitを使ってAPI通信をしてみよう！ 〜前編・API通信の実装〜](https://rightcode.co.jp/blog/information-technology/flutter-retrofit-api-1-syain)
○ [freezed パッケージの使い方【Flutter/Dart】](https://note.com/mxiskw/n/n55441444bd46)
○ [Flutter - json_serializableを理解するメモ](https://ryuichi111std.hatenablog.com/entry/2018/11/01/035333)
○ [Flutter x Riverpod でアプリ開発！実践入門](https://zenn.dev/riscait/books/flutter-riverpod-practical-introduction)
○[Flutter/Dartにおけるimmutableの実践的な扱い方](https://medium.com/flutter-jp/immutable-d23bae5c29f8)

2022-01-13 13:09 UTC, t-nakata requested changes

2022-01-13 13:09 UTC, t-nakata commented on .vscode/settings.json
> +}
![badge](https://img.shields.io/badge/review-ask-blue.svg)
辞書ファイルかな？このコードは意識して追加したものかな？
意識したものでなく、不要なら削除してください。
チーム開発で必要なもののみコミットするようにしてください。

2022-01-13 13:09 UTC, t-nakata commented on lib/mvvm/api/qiita_api_client.g.dart
> +class _QiitaApiClient implements QiitaApiClient {
![badge](https://img.shields.io/badge/review-imo-orange.svg)
チームの方針によって変わったりしますが、自動生成系のファイルは元ファイルがあれば
自動生成可能なので、各自がローカルでビルドして生成できるので、Gitで管理しない場合があります。

自分はコミットしない派だったりします。
今回はどちらでもいいですが、一応知識として知っておいてください。

2022-01-13 13:09 UTC, t-nakata commented on lib/mvvm/model/qiita_item.dart
> +// import 'package:training/mvvm/model/qiita_user.dart;
不要なコメントは削除してください

2022-01-13 13:09 UTC, t-nakata commented on lib/mvvm/qiita_client_screen.dart
> +        qiitaClientStateNotifier); // グローバル変数としてQiitaClientStateNotifierクラスを宣言
![badge](https://img.shields.io/badge/review-must-red.svg)
コメントが間違っています。グローバル変数ではなく、メソッド内のローカル変数です。

あと`state`の中身は`QiitaClientState`のインスタンスが入ります。

2022-01-13 13:09 UTC, t-nakata commented on lib/mvvm/qiita_client_screen.dart
> +      child: Scaffold(
![badge](https://img.shields.io/badge/review-must-red.svg)
インデントがずれているようです。
コミット前にFormatterを実行してください。

2022-01-13 13:44 UTC, t-nakata commented
ちょっと色々と細く

> Flutter社内研修Tutorial5「MMVMについて学ぶ」
MVVMです。

> ①Modelを作成
間違っているわけではないですが、MVVMで言うモデルってすごい範囲が広くて、View層とViewModel層以外を全部Model層と言ったりします。
つまり、RepositoryやAPIやDAOなどもModel層のオブジェクトなので総称でModelと呼んだりします。
詳しくはこの辺りを参照してください。
https://atmarkit.itmedia.co.jp/fdotnet/chushin/greatblogentry_02/greatblogentry_02_04.html

まあでも、Modelと言っても間違いではありません。

> ②Repositoryを作成
これも間違っているとかではないのですが、責務としてはデータを要求されたら、データを用意して返却する物となります。
データの用意の仕方は、Repository自体で定義しておいて、時にはメモリ上から取得したり、DBからロードしたり、サーバーからWebAPIを用いて取得したりします。
まあ、名前の通りGithubのローカルリポジトリを想像してもらえると分かりやすいと思います。

> ・Dio()は取得したJSONの中身を見たい時に使用。
これは間違いです。Dioは実際にHttp通信を行うクラスです。
Loggerをセットすることで中身を見ることができるようになります。

> ・QiitaClientState を継承することによって、親クラスであるQiitaClientState のプロパティを参照することができる。
これも間違いですね、QiitaClientStateNotifierはStateNotifierを継承していると表現します。
QiitaClientStateはジェネリクスで定義されているだけです。

StateNotifier<QiitaClientState>を継承すると、QiitaClientState型のオブジェクトを監視することができるStateNotifierとなります。

2022-01-14 01:07 UTC, gitknkn commented on .vscode/settings.json
> +}
@onishitaisei 
.vscodeディレクトリは基本的にgit管理対象外にした方が良いかと思います！
※.gitignoreファイルを確認した所、コメントアウトされているみたいです！

2022-01-14 01:09 UTC, gitknkn commented on .vscode/settings.json
> +}
@onishitaisei 
.vscodeフォルダーは基本的にgit管理対象外にした方が良いかと思います！
※.gitignoreファイルを確認した所、コメントアウトされているみたいです！

2022-01-14 05:26 UTC, sayaruri approved these changes

2022-01-14 05:26 UTC, sayaruri commented on pubspec.yaml
> +  flutter_state_notifier: ^0.7.1
ここのインポートいらないと思います！

2022-01-14 05:26 UTC, sayaruri commented on pubspec.yaml
> +  flutter_state_notifier: ^0.7.1
flutter_state_notifier: ^0.7.1

2022-01-14 05:36 UTC, Ryota-Nakamura-317 approved these changes

2022-01-14 08:08 UTC, gitknkn approved these changes

2022-01-14 08:22 UTC, onishitaisei commented on .vscode/settings.json
> +}
@t-nakata 
@gitknkn 
こちらのコードは意識してコミットしたものではありませんでした...
.vscodeディレクトリがgitの管理対象となっていたので、gitignoreに含めて管理対象外にしました！

2022-01-14 08:22 UTC, onishitaisei commented on pubspec.yaml
> +  flutter_state_notifier: ^0.7.1
レビューありがとうございます！
不要なインポートを削除いたしました..!

2022-01-14 08:24 UTC, onishitaisei commented on lib/mvvm/qiita_client_screen.dart
> +      child: Scaffold(
@t-nakata 
こちらFormatterで整形されるか試しましたが、何も変わらず、試しに上記のコードのインデントをわざと崩して試してみましたが、上記同様に整形される形でした。。

2022-01-14 08:26 UTC, onishitaisei commented on lib/mvvm/qiita_client_screen.dart
> +        qiitaClientStateNotifier); // グローバル変数としてQiitaClientStateNotifierクラスを宣言
@t-nakata 
こちらのコメントは不要と判断したので削除いたしました..!

2022-01-14 08:57 UTC, t-nakata approved these changes

2022-01-14 08:57 UTC, t-nakata commented on lib/mvvm/qiita_client_screen.dart
> +      child: Scaffold(
@onishitaisei 
では今回は対応無しで大丈夫です。

2022-01-14 08:58 UTC, t-nakata commented on lib/mvvm/model/qiita_item.dart
> +// import 'package:training/mvvm/model/qiita_user.dart;
@onishitaisei 
これもコメントが欲しかった

2022-01-14 09:25 UTC, merged